### ISSUE TITLE
dev/isp2020 year_correction_factor throwing error

### ISSUE THREAD

**Issue by BlakeKirby** [openCEMorg/openCEM#21]
Hi, I'm trying to run dev/isp2020 branch and have run into an error. It seems like model.t is not set. See output below:

![image](https://user-images.githubusercontent.com/47770150/93029581-51079980-f65f-11ea-82e7-cdbfc08fa254.png)

**Comment by jotaigna** [comment]
Thank you for notifying us of this issue.
In this case, this occured because the query to the database did not return a time series, so a subsequent processing of the data (i.e. to compute ycf) failed. In particular you are using the ISP 2020 database which is still in development and may at times be down. We hope to have a stable version of this database by the end of the month (famous last words...)
