### ISSUE TITLE
Dependency Testing - solver variations and versions

### ISSUE THREAD

**Issue by jufemaiz** [openCEMorg/openCEM#3]
With Docker we should be able to ensure that a set of dependencies are tested against (different combinations of solvers and their versions)

Ref: https://github.com/openCEMorg/openCEM/pull/2

**Comment by jotaigna** [comment]
I think this is a good suggestion. It is highly desirable to create a docker image that can be used for unit testing and coverage (and eventually automated pypi releases, etc) therefore testing for solver dependencies flows naturally from that. 

However it has limited applicability when it comes to different combinations of solvers because:
* glpk does not solve full size cases
* cbc <2.9.8 does not solve full size cases either
* ipopt ditto
* Commercial solvers have not been available for testing and probably not available on Docker
* Other solvers have not been tested because their licenses are not fully open (e.g. SCIP)
So at present, there is only cbc 2.9.9 and up. Which is still fine.

There is definitely scope to ensure that openCEM works across multiple versions of Python 3, as some tests for json files that work in 3.6 do not work in 3.7. But perhaps we should break this into multiple issues so we can work on them orderly.
